### ISSUE TITLE
Port MouseTrap to OpenCV 3.0

### ISSUE THREAD

**Issue by StoneyJackson** [Mousers/mousetrap#10]
https://bugzilla.gnome.org/show_bug.cgi?id=737303

**Comment by max12187** [comment]
Is this issue supposed to be a size 1? I thought it was 100.

**Comment by StoneyJackson** [comment]
Yup... looks like I messed that up.

**Comment by StoneyJackson** [comment]
This issue has been converted into an a milestone.
