### ISSUE TITLE
Testing Script further with partial/incorrect installs before use.

### ISSUE THREAD

**Issue by JESchulz** [Mousers/mousetrap#101]

**Comment by andrewgalisa** [comment]
Helping john with the testing

**Comment by andrewgalisa** [comment]
Ran the script and saw no problems with the install

**Comment by collaj** [comment]
I updated the script so pulling it down from branch issue#17s4 and testing will be beneficial since there are a few changes to it.

**Comment by JESchulz** [comment]
I'll be doing some more testing over this weekend with the new script as I had hardware issues which inhibited progress for it last night, and Alex has stated he's already used the new script in a fresh install environment and had no problems.

**Comment by JESchulz** [comment]
The script seems to work fine.  I tried replicating the errors I was getting under the previous "bad" install using openCV2 and had no problems this run-through.  I think it's safe to say at this point that the script works totally.
