### ISSUE TITLE
745088: Update to opencv-3.0-beta

### ISSUE THREAD

**Issue by StoneyJackson** [Mousers/mousetrap#113]

**Comment by HeidiEllis** [comment]
Summary of changes: http://opencv.org/opencv-3-0-beta.html

**Comment by tommanolakis** [comment]
Updated to OpenCV 3 Beta. I am still getting the same thing that I posted in #100. It seems that when the face is detected the video feed lags, or even comes to a complete halt, but when the face is not detected the video feed will process completely fine.

**Comment by tnormoyle** [comment]
I  finished updating to OpenCV 3 Beta. I also did not notice any differences in how mousetrap runs with OpenCV 3 alpha versus the beta. The video feed was still clear and detection was still working as well.

**Comment by ashleyredzko** [comment]
Must update dependency install script.

**Comment by kcarriere** [comment]
A few notes on installing the beta with the script:
-  If you used the script to install alpha, you have to delete the 'vendor' folder in /mousetrap, or at least delete the opencv folder in /mousetrap/vendor for the script to work for the install of beta
- There are 2 places to change '3.0.0-alpha' to '3.0.0-beta' in the script, make sure to change both
- You may want to change 'make -j4' if you are on a beefier computer, to speed the installs up a bit
- If you want to double-check you are using the beta, you can open python and check with:

> > python3
> > 
> > >>import cv2
> > 
> > >>cv2.__version__

and this should print '3.0.0-beta'

**Comment by kcarriere** [comment]
As for results, the beta functions similarly to the alpha, with no noticeable differences

**Comment by tommanolakis** [comment]
The script worked fine for both the alpha and beta, and I changed what Keith mentioned from make -j4 to make -j8 to speed up the installation since my processor supports 8 threads.

**Comment by WilliamAgoh** [comment]
The script work correctly for both alpha and beta, I just followed the tutorial made by Keith and everything seem to work perfectly.

**Comment by tnormoyle** [comment]
I tested it with the script using Keith's tutorial, and I found no noticeable differences between alpha and beta.

**Comment by ashleyredzko** [comment]
Tested on fedora 20. Found no noticeable differences.

**Comment by ashleyredzko** [comment]
Patch: https://www.dropbox.com/s/w5hdqxliiwyipib/OpenCV3-betadependencyupdate.patch?dl=0
