### ISSUE TITLE
Update dependencies in config files

### ISSUE THREAD

**Issue by StoneyJackson** [Mousers/mousetrap#14]
https://bugzilla.gnome.org/show_bug.cgi?id=737327
epic: https://bugzilla.gnome.org/show_bug.cgi?id=737303

**Comment by ashleyredzko** [comment]
Autogen is actually already configured for python3 and we don't need to change the configure.ac. Kevin Brown showed me a way to configure autogen.sh when we run the command to force it to choose python3.

PYTHON=$(which python3) ./autogen.sh

I plan on updating the README.

**Comment by ashleyredzko** [comment]
Branch issue#14 created. Pushed a README change that illustrated what to do for python2 or python3. Tested in Fedora 21, need test done in Ubuntu (I do not have this environment set up).
