### ISSUE TITLE
#19 Post patch.

### ISSUE THREAD

**Issue by JESchulz** [Mousers/mousetrap#144]

**Comment by adamdevigili** [comment]
Haven't been able to post any patch due to Github currently undergoing a DDoS attack. 
(http://www.zdnet.com/article/github-suffers-largest-ddos-attack-in-sites-history/)

**Comment by adamdevigili** [comment]
Patch posted to Bugzilla 
https://bugzilla.gnome.org/show_bug.cgi?id=739540
