### ISSUE TITLE
#83 Squash Branch

### ISSUE THREAD

**Issue by ashleyredzko** [Mousers/mousetrap#155]
Squash branch https://github.com/Mousers/mousetrap/tree/issue%2383s4

**Comment by StoneyJackson** [comment]
Looks like you'll need to clean up the style before you squash and commit:
https://travis-ci.org/Mousers/mousetrap/jobs/55546019

**Comment by ashleyredzko** [comment]
Reviewed and fixed errors in: https://github.com/Mousers/mousetrap/tree/issue%2383s5 

Will test and squash tomorrow in lab.

**Comment by ashleyredzko** [comment]
Squashed to https://github.com/Mousers/mousetrap/tree/issue%2383s5-squashed.
