### ISSUE TITLE
Read  X, Y from pointer to support testing

### ISSUE THREAD

**Issue by HeidiEllis** [Mousers/mousetrap#172]

**Comment by HeidiEllis** [comment]
Look at documentation from GDK to see how this is done.

**Comment by max12187** [comment]
http://www.pygtk.org/pygtk2reference/class-gdkwindow.html#method-gdkwindow--get-position

**Comment by JESchulz** [comment]
The call for getting the mouse position is here:
http://www.pygtk.org/pygtk2reference/class-gdkwindow.html#method-gdkwindow--get-pointer

**Comment by StoneyJackson** [comment]
Already implemented as `mousetrap.gui.Pointer.get_position`. Closing this issue.
