### ISSUE TITLE
#117 Identify Plugins

### ISSUE THREAD

**Issue by WilliamAgoh** [Mousers/mousetrap#174]

**Comment by WilliamAgoh** [comment]
I need to : 
         List available plugins
         Describe available plugins
         Provide a way of enable/disable plugins

**Comment by TrevorBreton** [comment]
Are you available tomorrow late morning to work on this with me?

**Comment by kcarriere** [comment]
Are you going to the cs lab to work on this? I can help as well on Thursday after 2pm

**Comment by TrevorBreton** [comment]
Results back in #117
