### ISSUE TITLE
#116 Research developing a plugin

### ISSUE THREAD

**Issue by collaj** [Mousers/mousetrap#175]
Research and learn how to create a plugin so that we may convert the standalone "track bright object" to plugin

**Comment by max12187** [comment]
I'm working with James on this.

**Comment by JESchulz** [comment]
Oh boy!  Can I come too?

**Comment by collaj** [comment]
I researched and created a simple test plugin that counts just to show it working.  I didn't have the time to do any testing with the config file.  I suggest that we look into and test loading values from the config file in case we need to for our plugin.

Here is the commit for what I have done so far: https://github.com/Mousers/mousetrap/commit/75d505dab4391f2e98ccf575df6d5f3f2f51af2d

**Comment by max12187** [comment]
I added code that reads data that I added to the config file and prints it out.  
Here is my commit: https://github.com/Mousers/mousetrap/commit/505307cfa0d9a1742153794e38fb3f7c2f5a9906
