### ISSUE TITLE
739540: As a user, I want MouseTrap to reflect accurate colors so that I can ensure that what I am seeing is accurate.

### ISSUE THREAD

**Issue by StoneyJackson** [Mousers/mousetrap#19]
https://bugzilla.gnome.org/show_bug.cgi?id=739540

**Comment by TrevorBreton** [comment]
Me and William are working on putting our code changes(from last semester) that fixed this issue into a patch. My patch will not work because it contained the updated haar files.

**Comment by adamdevigili** [comment]
Patch posted to bugzilla

**Comment by StoneyJackson** [comment]
Travis-CI is detecting formatting problems on PR #107. If you click through, you should eventually reach this: https://travis-ci.org/Mousers/mousetrap/jobs/52136364 . Lines 135-139 are telling you about formatting problems. You should be able to reproduce the check locally by running either `make lint` or `bin/lint.bash` in the root of the project. These need to get cleaned up before submitting a patch.

**Comment by adamdevigili** [comment]
Uploaded new patch with fixes to bugzilla

**Comment by adamdevigili** [comment]
Uploaded correctly formatted and squashed patch to Bugzilla

**Comment by StoneyJackson** [comment]
We can't get a GUI up, so we can't test. Please be prepared to demo in class today.

**Comment by ashleyredzko** [comment]
Note: #83 has a pull request, it unintentionally fixed the color. I recommend checking it out.
