### ISSUE TITLE
743813: Readme Uninstall Directions

### ISSUE THREAD

**Issue by ashleyredzko** [Mousers/mousetrap#27]
As a user, I want the ability to remove MouseTrap. Currently, the Readme doesn't tell me how to do that.

bugzilla tracker: https://bugzilla.gnome.org/show_bug.cgi?id=743813

**Comment by StoneyJackson** [comment]
Nice story card! Before we can prioritize this work, we need this reported to bugzilla.gnome.org. Once reported there, please paste a link to it here. Thanks!!!

**Comment by SClawz** [comment]
The patch has been posted.

**Comment by SClawz** [comment]
Isn't the above bugzilla tracker link the one you use to get to the bug? Or do I need to post the actual link to the exact addition. The link above has my README.md change in the comments

**Comment by StoneyJackson** [comment]
See bugzilla for feedback.

**Comment by SClawz** [comment]
Just posted the new patch, things should be in order now.
