### ISSUE TITLE
Install Python 3 and OpenCV 3

### ISSUE THREAD

**Issue by tommanolakis** [Mousers/mousetrap#33]
Necessary for testing #14

**Comment by tommanolakis** [comment]
Receiving an error where Python 3 doesn't recognize OpenCV 3 and will not import

**Comment by ashleyredzko** [comment]
Zane, James and myself co-authored a tutorial on this. You can find it here:

https://gist.github.com/collaj/e75c2f48f69e4e9dacdc

You can check the README in https://github.com/Mousers/mousetrap/tree/issue%2314 to see what command to use to force python3 or python2 (instead of changing AM_PATH_PYTHON in configure.ac).

**Comment by tommanolakis** [comment]
Tried this already and it didn't work (I'm on Ubuntu 14.04 LTS). I'm going to retry soon by uninstalling all dependencies and software and try a fresh build and see how it goes.

**Comment by StoneyJackson** [comment]
@tommanolakis When you try, if it fails, capture the results of your effort into a gist, and paste it here. You can use that as an artifact, and others might be able to help you identify the problem.

**Comment by tommanolakis** [comment]
Getting build errors while making OpenCV 3:

[ 58%] Generating core.cpp
Traceback (most recent call last):
  File "/home/tom2/opencv/opencv-3.0.0-beta/modules/java/generator/gen_java.py", line 1602, in <module>
    generator.gen(srcfiles, module, dstdir)
  File "/home/tom2/opencv/opencv-3.0.0-beta/modules/java/generator/gen_java.py", line 1105, in gen
    self.gen_class(ci)
  File "/home/tom2/opencv/opencv-3.0.0-beta/modules/java/generator/gen_java.py", line 1503, in gen_class
    for fi in ci.getAllMethods():
  File "/home/tom2/opencv/opencv-3.0.0-beta/modules/java/generator/gen_java.py", line 871, in getAllMethods
    result.extend([fi for fi in sorted(self.methods) if fi.isconstructor])
TypeError: unorderable types: FuncInfo() < FuncInfo()
make[2]: **\* [modules/java/core.cpp] Error 1
make[1]: **\* [modules/java/CMakeFiles/opencv_java.dir/all] Error 2
make[1]: **\* Waiting for unfinished jobs....
[ 62%] Built target opencv_test_photo
[ 62%] Built target opencv_perf_video
[ 62%] Built target opencv_test_video
make: **\* [all] Error 2

**Comment by tommanolakis** [comment]
Going to try a different tutorial for building OpenCV 3 on Ubuntu since this one doesn't seem to work

**Comment by kevin-brown** [comment]
@tommanolakis Probably the most helpful part of the output is what you get after running `cmake`, where it tells you all of the locations that have been detected.

You might also want to try skipping the Java modules by adding `-D BUILD_opencv_java=OFF` to the `cmake` command, as some people have reported issues building with it (and we disable it in our tests).

**Comment by tommanolakis** [comment]
Alright, so it worked after skipping the Java modules

**Comment by tommanolakis** [comment]
Now Python doesn't recognize OpenCV:

tom2@tom-MS-7851:~/mousetrap$ python3
Python 3.4.0 (default, Apr 11 2014, 13:05:11) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.

> > > import cv
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: No module named 'cv'
> > > import cv2
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: No module named 'cv2'

Does this mean it didn't install correctly?

**Comment by kevin-brown** [comment]
> Probably the most helpful part of the output is what you get after running `cmake`, where it tells you all of the locations that have been detected.

Most likely CMake was not able to find your Python locations correctly.

**Comment by tommanolakis** [comment]
tom2@tom-MS-7851:~/opencv/opencv-3.0.0-alpha/release$ make -j8
[  0%] Built target opencv_perf_core_pch_dephelp
[  5%] Built target libwebp
[  5%] [  5%] [  5%] Built target opencv_core_pch_dephelp
Built target opencv_ts_pch_dephelp
[  5%] Built target opencv_imgcodecs_pch_dephelp
Built target opencv_imgproc_pch_dephelp
[  5%] [  5%] Built target opencv_highgui_pch_dephelp
[  5%] Built target opencv_videoio_pch_dephelp
Built target opencv_test_core_pch_dephelp
[  5%] Built target opencv_perf_imgproc_pch_dephelp
[  5%] Built target opencv_perf_videoio_pch_dephelp
[  5%] Built target opencv_test_imgproc_pch_dephelp
[  5%] Built target opencv_test_videoio_pch_dephelp
[  5%] Built target opencv_test_flann_pch_dephelp
[  5%] Built target opencv_flann_pch_dephelp
[  5%] Built target opencv_test_highgui_pch_dephelp
[  5%] Built target opencv_perf_imgcodecs_pch_dephelp
[  5%] Built target opencv_test_imgcodecs_pch_dephelp
[ 10%] [ 10%] Built target opencv_perf_features2d_pch_dephelp
Built target opencv_test_features2d_pch_dephelp
[ 15%] Built target opencv_features2d_pch_dephelp
[ 15%] Built target opencv_perf_calib3d_pch_dephelp
[ 15%] Built target opencv_calib3d_pch_dephelp
[ 15%] Built target opencv_test_calib3d_pch_dephelp
[ 15%] [ 15%] [ 15%] Built target opencv_perf_objdetect_pch_dephelp
Built target opencv_test_objdetect_pch_dephelp
Built target opencv_test_ml_pch_dephelp
[ 15%] [ 15%] Built target opencv_ml_pch_dephelp
Built target opencv_objdetect_pch_dephelp
[ 15%] Built target opencv_perf_photo_pch_dephelp
[ 15%] Built target opencv_photo_pch_dephelp
[ 15%] Built target opencv_test_photo_pch_dephelp
[ 15%] [ 15%] Built target opencv_test_video_pch_dephelp
Built target opencv_perf_video_pch_dephelp
[ 15%] [ 15%] [ 15%] [ 15%] [ 15%] Built target opencv_video_pch_dephelp
Built target opencv_stitching_pch_dephelp
Built target opencv_perf_stitching_pch_dephelp
Built target opencv_shape_pch_dephelp
Built target opencv_test_shape_pch_dephelp
[ 15%] Built target opencv_test_stitching_pch_dephelp
[ 15%] Built target pch_Generate_opencv_ts
[ 15%] Built target opencv_videostab_pch_dephelp
[ 15%] Built target pch_Generate_opencv_core
[ 15%] Built target opencv_test_superres_pch_dephelp
[ 15%] [ 15%] Built target opencv_perf_superres_pch_dephelp
Built target opencv_superres_pch_dephelp
[ 15%] Built target opencv_test_viz_pch_dephelp
[ 15%] Built target pch_Generate_opencv_imgproc
[ 15%] Built target pch_Generate_opencv_imgcodecs
[ 15%] Built target pch_Generate_opencv_videoio
[ 15%] Built target pch_Generate_opencv_highgui
[ 15%] [ 15%] Built target pch_Generate_opencv_perf_core
Built target pch_Generate_opencv_test_core
[ 15%] Built target pch_Generate_opencv_test_flann
[ 15%] [ 15%] Built target pch_Generate_opencv_flann
Built target pch_Generate_opencv_perf_imgproc
[ 15%] Built target pch_Generate_opencv_test_imgproc
[ 15%] [ 15%] [ 15%] [ 15%] [ 15%] Built target pch_Generate_opencv_test_imgcodecs
Built target pch_Generate_opencv_perf_imgcodecs
Built target pch_Generate_opencv_test_videoio
Built target pch_Generate_opencv_perf_videoio
Built target pch_Generate_opencv_test_highgui
[ 21%] Built target pch_Generate_opencv_features2d
[ 21%] Built target pch_Generate_opencv_perf_features2d
[ 21%] Built target opencv_viz_pch_dephelp
[ 21%] [ 21%] Built target pch_Generate_opencv_calib3d
Built target pch_Generate_opencv_test_features2d
[ 21%] [ 21%] [ 21%] [ 21%] Built target pch_Generate_opencv_test_calib3d
Built target pch_Generate_opencv_perf_calib3d
Built target pch_Generate_opencv_ml
Built target pch_Generate_opencv_test_ml
[ 21%] Built target pch_Generate_opencv_objdetect
[ 21%] [ 21%] [ 21%] Built target pch_Generate_opencv_perf_objdetect
Built target pch_Generate_opencv_test_objdetect
Built target pch_Generate_opencv_perf_photo
[ 21%] [ 21%] [ 21%] Built target pch_Generate_opencv_photo
Built target pch_Generate_opencv_perf_video
Built target pch_Generate_opencv_video
[ 21%] Built target pch_Generate_opencv_test_photo
[ 21%] Built target pch_Generate_opencv_test_video
[ 21%] Built target pch_Generate_opencv_perf_stitching
[ 21%] [ 21%] Built target pch_Generate_opencv_test_stitching
Built target pch_Generate_opencv_stitching
[ 21%] [ 21%] [ 21%] Built target pch_Generate_opencv_test_shape
Built target pch_Generate_opencv_shape
Built target pch_Generate_opencv_perf_superres
[ 26%] Built target pch_Generate_opencv_superres
[ 26%] [ 26%] [ 26%] Built target pch_Generate_opencv_videostab
Built target pch_Generate_opencv_test_viz
Built target pch_Generate_opencv_test_superres
[ 31%] Built target pch_Generate_opencv_viz
[ 36%] Built target opencv_core
[ 36%] Built target opencv_flann
[ 42%] Built target opencv_ml
[ 42%] Built target opencv_viz
[ 47%] Built target opencv_imgproc
[ 47%] Built target opencv_video
[ 47%] Built target opencv_photo
[ 47%] Built target opencv_imgcodecs
[ 47%] Built target opencv_shape
[ 52%] Built target opencv_videoio
[ 52%] Built target opencv_superres
[ 52%] Built target opencv_highgui
[ 52%] Built target opencv_objdetect
[ 52%] Built target opencv_ts
[ 52%] Built target opencv_features2d
[ 52%] Built target opencv_test_flann
[ 52%] Built target opencv_perf_imgcodecs
[ 52%] Built target opencv_test_imgcodecs
[ 52%] Built target opencv_perf_videoio
[ 57%] Built target opencv_perf_core
[ 63%] Built target opencv_perf_imgproc
[ 63%] Built target opencv_test_core
[ 63%] Built target opencv_test_highgui
[ 68%] Built target opencv_test_imgproc
[ 68%] Built target opencv_test_videoio
[ 68%] Built target opencv_perf_features2d
[ 68%] Built target opencv_test_ml
[ 68%] Built target opencv_perf_objdetect
[ 68%] Built target opencv_test_objdetect
[ 68%] Built target opencv_test_features2d
[ 68%] Built target opencv_perf_photo
[ 68%] Built target opencv_test_photo
[ 73%] Built target opencv_calib3d
[ 73%] [ 73%] Built target opencv_perf_superres
Built target opencv_test_superres
[ 78%] Built target opencv_perf_video
[ 84%] Built target opencv_test_shape
[ 84%] Built target opencv_test_video
[ 89%] Built target opencv_test_viz
[ 89%] Built target opencv_perf_calib3d
[ 89%] Built target opencv_traincascade
[ 94%] Built target opencv_test_calib3d
[100%] Built target opencv_stitching
[100%] Built target opencv_videostab
[100%] Built target opencv_test_stitching
[100%] Built target opencv_perf_stitching
tom2@tom-MS-7851:~/opencv/opencv-3.0.0-alpha/release$

**Comment by tommanolakis** [comment]
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/vtk-5.8/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "vtkGenericFilteringTCL" references the file
   "/usr/lib/libvtkGenericFilteringTCL.so.5.8.0"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/vtk-5.8/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "vtkGenericFilteringPythonD" references the file
   "/usr/lib/libvtkGenericFilteringPythonD.so.5.8.0"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/vtk-5.8/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "vtkGenericFilteringJava" references the file
   "/usr/lib/jni/libvtkGenericFilteringJava.so.5.8.0"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/vtk-5.8/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "vtkIOTCL" references the file
   "/usr/lib/libvtkIOTCL.so.5.8.0"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/vtk-5.8/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "vtkIOPythonD" references the file
   "/usr/lib/libvtkIOPythonD.so.5.8.0"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/vtk-5.8/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "vtkIOJava" references the file
   "/usr/lib/jni/libvtkIOJava.so.5.8.0"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/vtk-5.8/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "vtkRenderingTCL" references the file
   "/usr/lib/libvtkRenderingTCL.so.5.8.0"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/vtk-5.8/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "vtkRenderingPythonD" references the file
   "/usr/lib/libvtkRenderingPythonD.so.5.8.0"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/vtk-5.8/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "vtkRenderingJava" references the file
   "/usr/lib/jni/libvtkRenderingJava.so.5.8.0"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/vtk-5.8/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "vtkRenderingPythonTkWidgets" references the file
   "/usr/lib/libvtkRenderingPythonTkWidgets.so.5.8.0"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/vtk-5.8/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "vtkVolumeRenderingTCL" references the file
   "/usr/lib/libvtkVolumeRenderingTCL.so.5.8.0"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/vtk-5.8/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "vtkVolumeRenderingPythonD" references the file
   "/usr/lib/libvtkVolumeRenderingPythonD.so.5.8.0"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/vtk-5.8/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "vtkVolumeRenderingJava" references the file
   "/usr/lib/jni/libvtkVolumeRenderingJava.so.5.8.0"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/vtk-5.8/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "vtkHybridTCL" references the file
   "/usr/lib/libvtkHybridTCL.so.5.8.0"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/vtk-5.8/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "vtkHybridPythonD" references the file
   "/usr/lib/libvtkHybridPythonD.so.5.8.0"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/vtk-5.8/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "vtkHybridJava" references the file
   "/usr/lib/jni/libvtkHybridJava.so.5.8.0"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/vtk-5.8/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "vtkWidgetsTCL" references the file
   "/usr/lib/libvtkWidgetsTCL.so.5.8.0"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/vtk-5.8/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "vtkWidgetsPythonD" references the file
   "/usr/lib/libvtkWidgetsPythonD.so.5.8.0"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/vtk-5.8/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "vtkWidgetsJava" references the file
   "/usr/lib/jni/libvtkWidgetsJava.so.5.8.0"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/vtk-5.8/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "vtkParallelTCL" references the file
   "/usr/lib/libvtkParallelTCL.so.5.8.0"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/vtk-5.8/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "vtkParallelPythonD" references the file
   "/usr/lib/libvtkParallelPythonD.so.5.8.0"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/vtk-5.8/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "vtkParallelJava" references the file
   "/usr/lib/jni/libvtkParallelJava.so.5.8.0"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/vtk-5.8/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "vtkInfovisTCL" references the file
   "/usr/lib/libvtkInfovisTCL.so.5.8.0"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/vtk-5.8/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "vtkInfovisPythonD" references the file
   "/usr/lib/libvtkInfovisPythonD.so.5.8.0"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/vtk-5.8/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "vtkInfovisJava" references the file
   "/usr/lib/jni/libvtkInfovisJava.so.5.8.0"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/vtk-5.8/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "vtkGeovisTCL" references the file
   "/usr/lib/libvtkGeovisTCL.so.5.8.0"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/vtk-5.8/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "vtkGeovisPythonD" references the file
   "/usr/lib/libvtkGeovisPythonD.so.5.8.0"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/vtk-5.8/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "vtkGeovisJava" references the file
   "/usr/lib/jni/libvtkGeovisJava.so.5.8.0"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/vtk-5.8/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "vtkViewsTCL" references the file
   "/usr/lib/libvtkViewsTCL.so.5.8.0"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/vtk-5.8/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "vtkViewsPythonD" references the file
   "/usr/lib/libvtkViewsPythonD.so.5.8.0"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/vtk-5.8/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "vtkViewsJava" references the file
   "/usr/lib/jni/libvtkViewsJava.so.5.8.0"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/vtk-5.8/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "vtkChartsTCL" references the file
   "/usr/lib/libvtkChartsTCL.so.5.8.0"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/vtk-5.8/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "vtkChartsPythonD" references the file
   "/usr/lib/libvtkChartsPythonD.so.5.8.0"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/vtk-5.8/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "vtkChartsJava" references the file
   "/usr/lib/jni/libvtkChartsJava.so.5.8.0"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/vtk-5.8/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "vtk" references the file
   "/usr/bin/vtk"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/vtk-5.8/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "pvtk" references the file
   "/usr/bin/pvtk"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/vtk-5.8/VTKTargets.cmake"
  but not all the files it references.

-- The imported target "vtkPythonCore" references the file
   "/usr/lib/libvtkPythonCore.so.5.8.0"
but this file does not exist.  Possible reasons include:
- The file was deleted, renamed, or moved to another location.
- An install or uninstall procedure did not complete successfully.
- The installation package was faulty and contained
  "/usr/lib/vtk-5.8/VTKTargets.cmake"
  but not all the files it references.

## -- Found VTK ver. 5.8.0 (usefile: /usr/lib/vtk-5.8/UseVTK.cmake)

-- General configuration for OpenCV 3.0.0-alpha =====================================

## --   Version control:               unknown

--   Platform:
--     Host:                        Linux 3.13.0-45-generic x86_64
--     CMake:                       2.8.12.2
--     CMake generator:             Unix Makefiles
--     CMake build tool:            /usr/bin/make

## --     Configuration:               RELEASE

--   C/C++:
--     Built as dynamic libs?:      YES
--     C++ Compiler:                /usr/bin/c++  (ver 4.8.2)
--     C++ flags (Release):         -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -msse -msse2 -msse3 -ffunction-sections -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
--     C++ flags (Debug):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -msse -msse2 -msse3 -ffunction-sections -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
--     C Compiler:                  /usr/bin/cc
--     C flags (Release):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wno-narrowing -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -msse -msse2 -msse3 -ffunction-sections -fvisibility=hidden -O3 -DNDEBUG  -DNDEBUG
--     C flags (Debug):             -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wno-narrowing -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -msse -msse2 -msse3 -ffunction-sections -fvisibility=hidden -g  -O0 -DDEBUG -D_DEBUG
--     Linker flags (Release):  
--     Linker flags (Debug):        

## --     Precompiled headers:         YES

--   OpenCV modules:
--     To be built:                 core flann imgproc imgcodecs videoio highgui features2d calib3d ml objdetect photo video shape stitching superres ts videostab viz
--     Disabled:                    world
--     Disabled by dependency:      -

## --     Unavailable:                 androidcamera cuda cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaoptflow cudastereo cudawarping cudev java python2 python3

--   GUI: 
--     QT:                          NO
--     GTK+ 2.x:                    YES (ver 2.24.23)
--     GThread :                    YES (ver 2.40.2)
--     GtkGlExt:                    NO
--     OpenGL support:              NO

## --     VTK support:                 YES (ver 5.8.0)

--   Media I/O: 
--     ZLib:                        /usr/lib/x86_64-linux-gnu/libz.so (ver 1.2.8)
--     JPEG:                        /usr/lib/x86_64-linux-gnu/libjpeg.so (ver )
--     WEBP:                        build (ver 0.3.1)
--     PNG:                         /usr/lib/x86_64-linux-gnu/libpng.so (ver 1.2.50)
--     TIFF:                        /usr/lib/x86_64-linux-gnu/libtiff.so (ver 42 - 4.0.3)
--     JPEG 2000:                   /usr/lib/x86_64-linux-gnu/libjasper.so (ver 1.900.1)
--     OpenEXR:                     /usr/lib/x86_64-linux-gnu/libImath.so /usr/lib/x86_64-linux-gnu/libIlmImf.so /usr/lib/x86_64-linux-gnu/libIex.so /usr/lib/x86_64-linux-gnu/libHalf.so /usr/lib/x86_64-linux-gnu/libIlmThread.so (ver 1.6.1)

## --     GDAL:                        NO

--   Video I/O:
--     DC1394 1.x:                  NO
--     DC1394 2.x:                  YES (ver 2.2.1)
--     FFMPEG:                      YES
--       codec:                     YES (ver 54.35.0)
--       format:                    YES (ver 54.20.4)
--       util:                      YES (ver 52.3.0)
--       swscale:                   YES (ver 2.1.1)
--       gentoo-style:              YES
--     GStreamer:  
--       base:                      YES (ver 0.10.36)
--       video:                     YES (ver 0.10.36)
--       app:                       YES (ver 0.10.36)
--       riff:                      YES (ver 0.10.36)
--       pbutils:                   YES (ver 0.10.36)
--     OpenNI:                      NO
--     OpenNI PrimeSensor Modules:  NO
--     OpenNI2:                     NO
--     PvAPI:                       NO
--     GigEVisionSDK:               NO
--     UniCap:                      NO
--     UniCap ucil:                 NO
--     V4L/V4L2:                    Using libv4l (ver 1.0.1)
--     XIMEA:                       NO

## --     Xine:                        NO

--   Other third-party libraries:
--     Use IPP:                     8.1.1 [8.1.1]
--          at:                     /home/tom2/opencv/opencv-3.0.0-alpha/3rdparty/ippicv/unpack/ippicv_lnx
--     Use IPP Async:               NO
--     Use Eigen:                   YES (ver 3.2.0)
--     Use TBB:                     NO
--     Use OpenMP:                  NO
--     Use GCD                      NO
--     Use Concurrency              NO
--     Use C=:                      NO
--     Use Cuda:                    NO

## --     Use OpenCL:                  YES

--   OpenCL:
--     Version:                     dynamic
--     Include path:                /home/tom2/opencv/opencv-3.0.0-alpha/3rdparty/include/opencl/1.2
--     Use AMDFFT:                  NO

## --     Use AMDBLAS:                 NO

--   Python 2:
--     Interpreter:                 /usr/bin/python3 (ver 3.4)
--     Libraries:                   NO
--     numpy:                       /usr/lib/python3/dist-packages/numpy/core/include (ver 1.8.2)

## --     packages path:               lib/python3.4/dist-packages

--   Python 3:
--     Interpreter:                 /usr/bin/python3.4 (ver 3.4)
--     Libraries:                   NO
--     numpy:                       /usr/lib/python3/dist-packages/numpy/core/include (ver 1.8.2)

## --     packages path:               lib/python3.4/dist-packages

## --   Python (for build):            NO

--   Java:
--     ant:                         /usr/bin/ant (ver 1.9.3)
--     JNI:                         /usr/lib/jvm/default-java/include /usr/lib/jvm/default-java/include /usr/lib/jvm/default-java/include

## --     Java tests:                  NO

--   Matlab:

## --     mex:                         NO

--   Documentation:
--     Build Documentation:         YES
--     Sphinx:                      /usr/bin/sphinx-build (ver 1.2.2)
--     PdfLaTeX compiler:           /usr/bin/pdflatex

## --     PlantUML:                    NO

--   Tests and samples:
--     Tests:                       YES
--     Performance tests:           YES

## --     C/C++ Examples:              NO

## --   Install path:                  /usr

--   cvconfig.h is in:              /home/tom2/opencv/opencv-3.0.0-alpha/release

---

## 

-- Configuring done
-- Generating done
-- Build files have been written to: /home/tom2/opencv/opencv-3.0.0-alpha/release
tom2@tom-MS-7851:~/opencv/opencv-3.0.0-alpha/release$

**Comment by tommanolakis** [comment]
@tredzko Did this work on your Ubuntu environment?

**Comment by ashleyredzko** [comment]
@tommanolakis I currently don't have a Ubuntu environment.

**Comment by SClawz** [comment]
@tommanolakis After class on Monday, we think that you should just try and switch to Fedora and install that.

**Comment by tommanolakis** [comment]
@SClawz going to install it either tonight or tomorrow
