### ISSUE TITLE
Installing OpenCV 3 and Mousetrap in Python 3

### ISSUE THREAD

**Issue by collaj** [Mousers/mousetrap#36]
This is necessary for testing issue #9

**Comment by collaj** [comment]
I created a tutorial on how to OpenCV 3 and Mousetrap in Python 3:
        https://gist.github.com/collaj/e75c2f48f69e4e9dacdc
This should help everyone who doesn't have the environment set up yet.

**Comment by StoneyJackson** [comment]
That's awesome!!
