### ISSUE TITLE
Test issue #9 fix

### ISSUE THREAD

**Issue by max12187** [Mousers/mousetrap#42]

**Comment by max12187** [comment]
Andrews fix worked for me. It now longer core dumps. The cursor is much more responsive but the picture is broken. It looks like a scrambled TV picture: https://www.dropbox.com/s/lxx79r9le05ajak/mousetrap_video.png?dl=0

**Comment by StoneyJackson** [comment]
@max12187 Did you add a story card to the backlog for this new problem? We don't want to lose this. If not, please add it.

**Comment by max12187** [comment]
@StoneyJackson I don't know if the problem only exists for me or if others are having it too. Should I still add the card?

**Comment by StoneyJackson** [comment]
@max12187 Absolutely. If you don't raise the issue, who will? If later it's determined to be "just for you", there is still a reason. And that might lead us to another problem. But that's still valuable.
