### ISSUE TITLE
For #9: create patch and post to bugzilla

### ISSUE THREAD

**Issue by StoneyJackson** [Mousers/mousetrap#44]
Squashed branch must be created first: #43

**Comment by max12187** [comment]
When I tried to upload the patch to bugzilla, I got this error: The file you are trying to attach is 7642 kilobytes (KB) in size. Patches cannot be more than 1600 KB in size. Try splitting your patch into several pieces. I don't know to go about this.

**Comment by StoneyJackson** [comment]
Post a reply to the Bugzilla with a link to the patch URL.

-Stoney

**Comment by max12187** [comment]
Done, thank you.
