### ISSUE TITLE
#83 Identify core issue

### ISSUE THREAD

**Issue by SClawz** [Mousers/mousetrap#47]
With issue #9, we don't know exactly what the problem is, or what is causing it. We need to identify the issue in order to work toward solving it.

**Comment by ashleyredzko** [comment]
From issue #56, the detection plugins are causing the video errors. Will have to dig deeper to see what in those plugins is causing the issue.

**Comment by ashleyredzko** [comment]
Issue change to #83

**Comment by ashleyredzko** [comment]
From issue#83s4 (clone of master), no longer receive scrambled video feed, receive OpenCL error when detection is on. As with error before, when detection is off, video feed is restored with incorrect colors and no errors. This still appears to be a detection issue.
