### ISSUE TITLE
For #17 Create/arrange the script for dependencies for mousetrap.

### ISSUE THREAD

**Issue by JESchulz** [Mousers/mousetrap#48]
Create Script for Issue 17 to install Mousetrap's Dependencies.

**Comment by collaj** [comment]
I created the script to install the dependencies for mousetrap on Fedora 21.  I tested and it worked on my machine which was a fresh install except for a few of the dependencies.
Here is the link to the commit on git: https://github.com/Mousers/mousetrap/commit/0cddd9ba5bbc3b4d91876b1317635c34b5c9f605

**Comment by JESchulz** [comment]
As an additional side note, the script will fail if the user attempting to install is not a pre-specified sudo user or root.  This is something to consider when using fedora as the first user account created will not be defaulted sudo privileges.   For the script not to fail halfway through, it either must be run as root or the user running it must be added to the list of sudo users via the following:
- At the terminal log in as root.
- type "visudo" (without quotes) into the terminal.  This will take you to the /etc/sudoers file to modify privileges in vi.
- Locate the bottom of the document (it's long) and add the following line once in insert mode (i):
  your_username ALL=(ALL) ALL
- If you would like to request no password while running, add NOPASSWD: ALL after the above.
- Leave insert mode and type :wq to write and quit.
- Reboot Fedora to have the privileges fully update.

It may be worth adding this to documentation regarding use of the install script.
