### ISSUE TITLE
For #17 Establish testing methods

### ISSUE THREAD

**Issue by JESchulz** [Mousers/mousetrap#51]
Decide on testing methods - VM's, re-installs of Fedora, etc.

**Comment by amarocchini** [comment]
For anyone who is interested in using  live fedora 21 on an external drive for testing, here is a tutorial. https://gist.github.com/amarocchini/bd3efdc513300c5eecd7

**Comment by amarocchini** [comment]
For anyone who would like to get away from Ubuntu and perform a hard install of Fedora 21 on an external drive, here is a tutorial. https://gist.github.com/amarocchini/5a254440192fe84bf21b
