### ISSUE TITLE
Replicate error in #9

### ISSUE THREAD

**Issue by ashleyredzko** [Mousers/mousetrap#67]

**Comment by ashleyredzko** [comment]
Able to replicate issue max had on issue#9 using https://github.com/Mousers/mousetrap/tree/issue%239-squashed and python3. Mousetrap no longer core dumps but video is just noise.

**Comment by ashleyredzko** [comment]
Note: This install is using python3 on fedora21 using installation guide from James, Zane and I, and README autogen instructions from isssue#14

**Comment by StoneyJackson** [comment]
What version of OpenCV? (I'm expecting/assuming 3)

**Comment by ashleyredzko** [comment]
Should be OpenCV3 (the alpha for python3).

**Comment by ashleyredzko** [comment]
Detection is working but the video feed is a mess.
