### ISSUE TITLE
Investigate possible fix for issue #9 and #19.

### ISSUE THREAD

**Issue by TrevorBreton** [Mousers/mousetrap#74]
TylerRedzko and I think we may have a fix for both of these issues. We are working on testing them on both of our setups. Post here for updates.

**Comment by ashleyredzko** [comment]
It looks like it fixes the colors along with allowing detection. However I'm currently running into another issue where OpenCL runtime fails and mousetrap either does not work or the video doesn't load. The error is what's seen here:
 http://stackoverflow.com/questions/25723059/failed-to-load-opencl-runtime-opencv3-python
Except that I have a problem that may be related to it.

Will be attempting to rebuild OpenCV without OpenCL.

**Comment by ashleyredzko** [comment]
image.py causes "Failure to load OpenCL Runtime".

**Comment by ashleyredzko** [comment]
Moving this back to the backlog, no longer investigating image.py as a possible fix. Unsure what to do with ticket.
