### ISSUE TITLE
Fix error "Failed to load OpenCL runtime"

### ISSUE THREAD

**Issue by ashleyredzko** [Mousers/mousetrap#75]
Since uninstalling my version of mousetrap on python3 and reinstalling for issue #9, I now receive the above error. The video feed will not show when detection is on. When detection is off, the video feed shows the first few seconds and then freezes.

Trevor was running into a similar error when I worked with him in the lab.

**Comment by tommanolakis** [comment]
http://www.nvidia.com/Download/driverResults.aspx/81760/en-us

**Comment by SClawz** [comment]
http://support.amd.com/en-us/kb-articles/Pages/Catalyst-Linux-Installer-Notes.aspx

Here is the "how" about installing drivers for amd opencl

**Comment by tommanolakis** [comment]
If the x-server is still running type 'sudo service lightdm stop' then execute the run command again and install the Nvidia driver. Once it has fully installed we need to start the x-server again so type 'sudo service lightdm start' then hit alt-f7 to get back into the desktop gui

**Comment by tommanolakis** [comment]
I forgot to add that before you do this you need to go into the terminal only mode, so hit alt-f1 while on the desktop

**Comment by SClawz** [comment]
Using mouetrap issue #9 and the image.py that both Tyler and Trevor are using, I'm now running into the same problem.

**Comment by ashleyredzko** [comment]
This error is related to the new image.py that Trevor provided to me. When building cleanly with issue#9-squashed branch, this error disappears.
