### ISSUE TITLE
Get connected

### ISSUE THREAD

**Issue by ashleyredzko** [Mousers/mousetrap#8]

**Comment by StoneyJackson** [comment]
- [x] Create GitHub account
- [x] Create waffle.io account
- [x] Create bugzilla.gnome.org account
- [x] Join MouseTrap email list
- [x] Install IRC client
- [x] connect to irc://irc.gnome.org/mousetrap
- [x] read up on MouseTrap: https://wiki.gnome.org/Projects/MouseTrap
