### ISSUE TITLE
745051: Fix video feed error

### ISSUE THREAD

**Issue by StoneyJackson** [Mousers/mousetrap#83]
https://bugzilla.gnome.org/show_bug.cgi?id=745051

It's grey-scale grainy junk.

**Comment by StoneyJackson** [comment]
From #9

**Comment by ashleyredzko** [comment]
Currently working in #47. Detection plugins are causing the video feed to fail. When disabled, the feed is fixed (though in wrong colors).

**Comment by TrevorBreton** [comment]
We have created a branch, issue83s4, that has produced working code for the part of our team that has tested it. Waiting on a few others to test but I anticipate them getting the same results.

**Comment by ashleyredzko** [comment]
Testing of possible fix #100

**Comment by ashleyredzko** [comment]
Patch was too large to upload on bugzilla. Provided drop box link:
https://www.dropbox.com/s/sg9r8w60addsdnq/VideoFix.patch?dl=0

**Comment by StoneyJackson** [comment]
GUI isn't displaying, so we can't test. Please be prepared to demo in class today.
