### ISSUE TITLE
#83 Create/Test Branch Pre-existing

### ISSUE THREAD

**Issue by TrevorBreton** [Mousers/mousetrap#89]
I have working code that does not core dump, tracks somewhat properly, and has correct color display. It also does not have the video feed error. I am working on creating a branch for this code and pushing it so that other members of my team can pull it down to their setups and test it.

**Comment by TrevorBreton** [comment]
William will be working with me in the lab around 1:15 to create/test the branch.

**Comment by SClawz** [comment]
How are you guys doing on this?

**Comment by TrevorBreton** [comment]
Was unable to get into the lab at the time mentioned above. Will get into the lab this weekend to get this done.

**Comment by TrevorBreton** [comment]
After trying this out in the lab and talking with Stoney during the scrum Friday, I was unsure exactly where he thinks this code should be put. I am working with Tyler at 4:15 tomorrow(Tuesday) as he has a better understanding of where I need to put this.

**Comment by TrevorBreton** [comment]
Time of meeting with Tyler changed to 11:50 Wednesday.

**Comment by ashleyredzko** [comment]
Met with Trevor and tried to rebase off of our branch issue#83s4. Ran into some issues. After investigating, found the the image.py and haar files were the main differences outside of code cleanup. When using the new image.py and old haar files on the lab computer (3rd from left) without OpenCL support in OpenCV, mousetrap works with correct color, has some detection (though it is buggy), and the image is clear! Zane is with me testing these changes with a fresh install.

Branch: https://github.com/Mousers/mousetrap/tree/issue%2383s4

**Comment by SClawz** [comment]
Just tested a bunch and here's what we got: (done on cs lab pc 2nd from left)

   -With opencl
Everything works fine. Video, color, and tracking. It is a bit laggy, and we still get the v4l error, but it works much better than it did.

   -Without opencl
No difference, everything worked just as above

Everything was done with python 3.

**Comment by ashleyredzko** [comment]
With this test, I'd say it's safe to move this to complete and start moving toward testing. We can test in #100.
