### ISSUE TITLE
MouseTrap core dumps upon startup with Python 3 and OpenCV3

### ISSUE THREAD

**Issue by StoneyJackson** [Mousers/mousetrap#9]
https://bugzilla.gnome.org/show_bug.cgi?id=737612
epic: https://bugzilla.gnome.org/show_bug.cgi?id=737303

**Comment by StoneyJackson** [comment]
- [] find updated haar files
- [] test
- [] test of patch
- [] review comments

**Comment by andrewgalisa** [comment]
Okay guys so I pushed up my squashed commit of the mousetrap with the updated haar  cascade files.  So far so good on my local laptop.  Also for those who haven't installed mousetrap under python 3 here's two links showing the steps and instructions:

http://blog.kevinbrown.in/programming/2014/09/27/building-and-installing-opencv-3.html#building-opencv

https://gist.github.com/kevin-brown/e52865f0641f04aa2e68

**Comment by StoneyJackson** [comment]
I'm not seeing it on branch `issue#9`
https://github.com/Mousers/mousetrap/commits/issue%239

**Comment by max12187** [comment]
I followed the link provided that installed opencv3. This failed for me. I am going to investigate this. I will update you guys on what I find.

**Comment by StoneyJackson** [comment]
@max12187 which link?

@andrewgalisa Where are the magic XML files that solve all the problems? URL preferable. You say you pushed your code. But I don't see it in any branches. Can you give the steps you took to "push" your code? When you do, can you also please post the result of `git remote -v`? That will show which remote repositories your local repository is linked to.

**Comment by StoneyJackson** [comment]
@max12187 you might also look the latest commit on [gnome3-wip](https://github.com/Mousers/mousetrap/tree/gnome3-wip). It contains a .travis.yml file which Travis-CI uses to install dependencies, including compiling opencv; build and install MouseTrap; and run all of its tests. It does this with help from some bash scripts in the bin/ directory. Mind you, the build and install is being done on Ubuntu 12.04, not Fedora. But it might give you some additional clues. Let me know if you have trouble understanding it.

**Comment by andrewgalisa** [comment]
my apologies I thought I had put the link in my other message
here it is:

http://alereimondo.no-ip.org/OpenCV/34

**Comment by StoneyJackson** [comment]
@andrewgalisa The problem is that your fix is not in the repository. Please either figure out how to get it pushed into the repository. Or tell your team how to make the fix. Remember if its not public, it didn't happen. Right now, not much is happening.

**Comment by StoneyJackson** [comment]
@andrewgalisa OK... I found your fork (https://github.com/andrewgalisa/mousetrap/tree/9b8f6d633960b3803688dfc2fe4fd96131a36476). I was expecting that folks would work directly on this repository. If not, that's fine, but you need to let everyone know where you are work. However, I highly recommend working in this repo, and on the branch named after this story. That will really help you and your team to stay aware of what you are doing. And they'll more easily be able to help you (since they have push access to this repo too). Plus, now, you still need to figure out how to get your work into this repository on branch `issue#9`. EDIT: I think if you make a pull request from your fork into this repo into branch `issue#9`. That might work.

**Comment by collaj** [comment]
I created a tutorial on how to OpenCV 3 and Mousetrap in Python 3:
        https://gist.github.com/collaj/e75c2f48f69e4e9dacdc
This should help everyone who doesn't have the environment set up yet in preparation for testing this issue.

**Comment by max12187** [comment]
That tutorial helped me greatly. Good job.

**Comment by StoneyJackson** [comment]
Closing #46 as a duplicate. (We thought this was going to be a different story, but it isn't.) Here is max's comment from that issue:

Title: video feed broken with issue#9 fix
Screen shot of the problem: https://www.dropbox.com/s/lxx79r9le05ajak/mousetrap_video.png?dl=0
