### ISSUE TITLE
Create/check logs within the Python files to isolate the problem

### ISSUE THREAD

**Issue by tommanolakis** [Mousers/mousetrap#93]

**Comment by ashleyredzko** [comment]
Is this for the video feed issue?  #83

**Comment by tommanolakis** [comment]
@tredzko Yes, I'm having trouble replicating the error though, I am supposed to be using squashed branch 9 for testing right?

**Comment by SClawz** [comment]
To do so, also with the help of Tyler:

mousetrap --dump-annotated > ~/mousetrap.yaml

Now change the ..yaml file that was created with
vi mousetrap.yaml

Then type
 mousetrap --config ~/mousetrap.yaml
to run mousetrap with your changes.

**Comment by tommanolakis** [comment]
Okay so I got it working on Branch issue 83s4

**Comment by tommanolakis** [comment]
When mousetraps noseJoystickPlugin or EyesPlugin get loaded in through mousetrap.yaml the video feed error occurs, and when these are loaded in mousetrap.vision runs. When these are disabled mousetrap.vision doesn't run and the video feed is showing up (still with the incorrect colors). However if I use the FeatureDetectorClearCachePlugin the video feed still works but if my face is in the image while mousetrap is initializing it will core dump but if my face comes into the image after mousetrap has initialized the core will not dump and I can leave my face in the image.

I'm still going to look more into the logs at what is being loaded and maybe where in mousetrap.vision the error is occurring.

**Comment by tommanolakis** [comment]
Want to work on this more once I install OpenCV 3 Beta to see if anything in the logs change
