### ISSUE TITLE
For #72 list files that involve observer pattern.

### ISSUE THREAD

**Issue by JESchulz** [Mousers/mousetrap#95]

**Comment by max12187** [comment]
So, after inspecting the code base, it seems that all the code involving the observer pattern is in "core.py" and encapsulated in the "App" object declared in this file. This App object is referenced and passed throughout the project. I think that if we are careful, we only need to change the code in "core.py". Someone else's input would be appreciated.

**Comment by max12187** [comment]
Files that reference the "App" object I described:
core.py
main.py
vision.py
plugins\camera.py
plugins\display.py
plugins\eyes.py
plugins\interface.py
plugins\nose.py

**Comment by JESchulz** [comment]
I can't find anything to dispute your claims.  I didn't see much in the realm of object creation and references beyond App and Loop, and nothing else seemed to inherit from Observable.

Hoping to get some votes for Monday's list to perhaps get some review for how to implement the event system for later on, as I'm assuming we'll be taking that task on.
