### ISSUE TITLE
#83 Investigate Detection

### ISSUE THREAD

**Issue by ashleyredzko** [Mousers/mousetrap#98]

**Comment by ashleyredzko** [comment]
Consolidating issue #97 in. Doesn't make sense to look at each detection piece separately.

**Comment by SClawz** [comment]
I'm going to help with this, and see what I can find...

**Comment by kcarriere** [comment]
I'm also looking into this. In line with what Tyler said, disabling each plugin seperately still causes the feed error, and disabling both produces a working video feed

**Comment by kcarriere** [comment]
Just realized I was working in the wrong branch, but seem to still be getting the scrambled feed in issue#83s4

Was there something more required than 'make clean' after making changes that needs to be done for mousetrap to compile those changes?

**Comment by ashleyredzko** [comment]
@kcarriere No, if you're making changes it will make a new build folder then. make clean will remove the build folder so nothing should be left of the previous compile.There are currently no committed changes to issue#83s4, so you should get the messed up feed.

**Comment by kcarriere** [comment]
Okay thanks. I misinterpreted your comment from #47, thinking 83s4 fixed the scrambled feed

**Comment by StoneyJackson** [comment]
Just thought I'd try.

Context:
- python3
- opencv 3-alpha

Try 1 Steps:
- Checkout issue#17s4
- run bin/install_prereq_fedora21_...bash script made by other team (which will compile and install opencv3-alpha)
- Checkout issue#83s4
- PYTHON=$(which python3) ./autogen.sh --prefix=/usr
- make & sudo make install
- mousetrap

Try 1 Results:
- Camera and detection are working
- No display
- When I interrupt with ctrl+C I get the ugly greyscale display

Try 2 Steps:
- Use config to disable all but the camera and display plugins

Try 2 Results:
- Core dump

Try 3 Steps:
- Disable display, enable all other plugins

Result:
- Tracks fine

In all cases I get VIDEOIO ERROR: V4L/V4L2: VIDIOC_S_CROP, even when it runs fine.

**Comment by ashleyredzko** [comment]
Investigating fix in #89, moved to backlog

**Comment by TrevorBreton** [comment]
This task should no longer be needed. Issue83s4 branch produced working code for all that have tested. Still have a few others to test but should be able to produce the same result.
